# Generated by Django 3.2.12 on 2022-02-15 13:03

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, unique=True)),
                ('category_slug', models.SlugField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta_title', models.CharField(max_length=255)),
                ('article_header_image_url', models.CharField(max_length=255)),
                ('article_description', models.TextField()),
                ('article_title', models.CharField(max_length=255)),
                ('article_content', tinymce.models.HTMLField()),
                ('article_published', models.DateTimeField(default=datetime.datetime(2022, 2, 15, 15, 3, 41, 425754), verbose_name='date publiched')),
                ('article_slug', models.SlugField(max_length=255, unique=True)),
                ('is_public', models.BooleanField(default=False)),
                ('article_category', models.ManyToManyField(to='app.Category')),
            ],
        ),
    ]
