<<<<<<< HEAD
# Generated by Django 3.2.12 on 2022-02-15 14:33
=======
# Generated by Django 3.2.12 on 2022-07-05 13:01
>>>>>>> 59f1744e004f7e3b77d41583f3c27ba6e15d83fa

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_published',
<<<<<<< HEAD
            field=models.DateTimeField(default=datetime.datetime(2022, 2, 15, 14, 33, 6, 623458), verbose_name='date publiched'),
=======
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 13, 1, 31, 853115), verbose_name='date publiched'),
>>>>>>> 59f1744e004f7e3b77d41583f3c27ba6e15d83fa
        ),
    ]
