# Generated by Django 3.2.12 on 2022-07-05 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_published',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 5, 15, 14, 28, 184291), verbose_name='date publiched'),
        ),
    ]
